# Generated by Django 3.2.3 on 2022-03-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_BodyType', models.CharField(max_length=50)),
                ('Car_FuelType', models.CharField(max_length=50)),
                ('Car_Transmission', models.CharField(max_length=50)),
            ],
        ),
    ]
