# Generated by Django 3.2.3 on 2022-03-02 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_brand',
            name='Car_Year',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
