# Generated by Django 3.2.3 on 2022-03-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carviewer', '0002_car_brand_car_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Name', models.CharField(max_length=50)),
                ('Car_Year', models.CharField(max_length=50)),
                ('Car_Prize', models.CharField(max_length=50)),
                ('Car_BodyType', models.CharField(max_length=50)),
                ('Car_FuelType', models.CharField(max_length=50)),
                ('Car_Transmission', models.CharField(max_length=50)),
                ('Car_Milage', models.CharField(max_length=50)),
            ],
        ),
    ]
