# Generated by Django 3.2.3 on 2022-03-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carviewer', '0003_car_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Brand', models.CharField(db_index=True, max_length=50)),
                ('Car_Year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Name', models.CharField(max_length=50)),
                ('Car_Year', models.IntegerField()),
                ('Car_Prize', models.CharField(max_length=50)),
                ('Car_BodyType', models.CharField(max_length=50)),
                ('Car_FuelType', models.CharField(max_length=50)),
                ('Car_Transmission', models.CharField(max_length=50)),
                ('Car_Milage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_BodyType', models.CharField(max_length=50)),
                ('Car_FuelType', models.CharField(max_length=50)),
                ('Car_Transmission', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Car_Brand',
        ),
        migrations.DeleteModel(
            name='Car_Model',
        ),
        migrations.DeleteModel(
            name='Car_Type',
        ),
    ]
