# Generated by Django 3.2.3 on 2022-03-16 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carviewer', '0004_auto_20220315_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='Car_Brand',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='carmodels', to='carviewer.carbrand'),
        ),
        migrations.AddField(
            model_name='cartype',
            name='Car_Brand',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartypes', to='carviewer.carbrand'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='Car_Brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='Car_Year',
            field=models.IntegerField(),
        ),
    ]
