# Generated by Django 3.2.3 on 2022-03-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carviewer', '0005_auto_20220315_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbrand',
            old_name='Car_Brand',
            new_name='car_brand',
        ),
        migrations.RenameField(
            model_name='carbrand',
            old_name='Car_Year',
            new_name='car_year',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='Car_BodyType',
            new_name='car_bodytype',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='Car_Brand',
            new_name='car_brand',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='Car_FuelType',
            new_name='car_fueltype',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='Car_Milage',
            new_name='car_milage',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='Car_Prize',
            new_name='car_prize',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='Car_Transmission',
            new_name='car_transmission',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='Car_Year',
            new_name='car_year',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='Model_Name',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='cartype',
            old_name='Car_BodyType',
            new_name='car_bodytype',
        ),
        migrations.RenameField(
            model_name='cartype',
            old_name='Car_Brand',
            new_name='car_brand',
        ),
        migrations.RenameField(
            model_name='cartype',
            old_name='Car_FuelType',
            new_name='car_fueltype',
        ),
        migrations.RenameField(
            model_name='cartype',
            old_name='Car_Transmission',
            new_name='car_transmission',
        ),
    ]
