# Generated by Django 3.2.3 on 2022-03-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carviewer', '0006_auto_20220316_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='car_milage',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='car_prize',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_mileage',
            field=models.CharField(default=20, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='car_year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_year',
            field=models.CharField(max_length=50),
        ),
    ]
