# Generated by Django 3.2.3 on 2022-03-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carviewer', '0007_auto_20220317_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_mileage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
