# Generated by Django 3.2.3 on 2022-03-18 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carviewer', '0009_alter_carbrand_car_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_year', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('car_bodytype', models.CharField(max_length=50)),
                ('car_expert_review', models.CharField(max_length=100)),
                ('car_user_review', models.CharField(max_length=100)),
                ('car_overall_review', models.CharField(max_length=100)),
                ('car_brand', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreviews', to='carviewer.carbrand')),
            ],
        ),
    ]
